import os

a = open('datas.txt','w')
a.write('alldata')
a.close()
os.system('python feat5.py 1 alldata')
os.system('python feat6.py 1 alldata')
os.system('python lgb_train.py 0 alldata')
os.system('python lgb_train.py 1 alldata')
os.system('python lgb_train.py 2 alldata')
os.system('python lgb_train.py 3 alldata')
os.system('python lgb_train.py 4 alldata')
os.system('python lgb_train.py 5 alldata')
os.system('python lgb_train.py 6 alldata')
os.system('python lgb_train.py 7 alldata')
os.system('python lgb_train.py 8 alldata')
os.system('python lgb_train.py 9 alldata')
os.system('python lgb_train.py 10 alldata')
# os.system('python ronghe.py')


a = open('datas.txt','w')
a.write('fu')
a.close()
os.system('python feat5.py 1 fu')
os.system('python feat6.py 1 fu')
os.system('python lgb_train.py 0 fu')
os.system('python lgb_train.py 1 fu')
os.system('python lgb_train.py 2 fu')
os.system('python lgb_train.py 3 fu')
os.system('python lgb_train.py 4 fu')
os.system('python lgb_train.py 5 fu')
os.system('python lgb_train.py 6 fu')
os.system('python lgb_train.py 7 fu')
os.system('python lgb_train.py 8 fu')
os.system('python lgb_train.py 9 fu')
os.system('python lgb_train.py 10 fu')
os.system('python ronghe.py')